
version: '3.8'
services:
  backend-digi-teste:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "start"]
